development:
  adapter: postgresql
  encoding: unicode
  database: ember-crm_development
  pool: 5
<% if Gem.win_platform? %>
  username: ember-crm_development
  password: only_need_in_windows
<% end %>

test:
  adapter: postgresql
  encoding: unicode
  database: ember-crm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ember-crm_production
  pool: 5
